### ISSUE TITLE
Linker issue when upgrading to Xcode 16

### ISSUE THREAD

**Issue by skewerb** [bdeweygit/unity-swiftui-demo#1]
When upgrading to Xcode 16, these error appears:

```
Undefined symbol: __mh_execute_header
Linker command failed with exit code 1 (use -v to see invocation)
```

The solution was found from this stackoverflow post:
https://stackoverflow.com/questions/78932936/undefined-symbols-for-architecture-arm64-mh-execute-header-unity-as-a-lib

The change would be in Unity.swift

Would just need to modify

```
let machineHeader = UnsafeMutablePointer<MachHeader>.allocate(capacity: 1)
machineHeader.pointee = _mh_execute_header
framework.setExecuteHeader(machineHeader)
```
to:

```
let machineHeader = #dsohandle.assumingMemoryBound(to: MachHeader.self)
framework.setExecuteHeader(machineHeader)
```

This update fixes the linker issue in Xcode 16, but I haven't verified with other versions

**Comment by bdeweygit** [comment]
I think Unity's CrashReporter will be relying on the header data in `machineHeader.pointee`, so we need to confirm that we are still passing the exact same header.
```swift
// Compare headers
let h1 = UnsafeMutablePointer<MachHeader>.allocate(capacity: 1)
h1.pointee = _mh_execute_header
let h2 = #dsohandle.assumingMemoryBound(to: MachHeader.self)
print(h1.pointee)
print(h2.pointee)
```
```
mach_header_64(magic: 4277009103, cputype: 16777228, cpusubtype: 0, filetype: 2, ncmds: 50, sizeofcmds: 5592, flags: 2097285, reserved: 0)
mach_header_64(magic: 4277009103, cputype: 16777228, cpusubtype: 0, filetype: 2, ncmds: 50, sizeofcmds: 5592, flags: 2097285, reserved: 0)
```
Looks like they match. Is this always true? Within an executable's code I think yes. Within a dynamic shared object's code I think probably not? Our case is the former so this should be safe, although using `#dsohandle` feels semantically wrong since this is an iOS app not a shared library. 

I'm also confused about the state of this bug. In [the apple forum](https://forums.developer.apple.com/forums/thread/760543) someone says this issue (123416939) is under **Known Issues** in the [Xcode 16 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes), but it is actually under **Resolved Issues**. Did it move? Is it or will it soon be fixed? Not sure. In any case, I'm getting the same undefined symbol error on Xcode 16. I'll update the project and If I learn that `_mh_execute_header` really is the best practice then I can revert back to it  if/when Xcode eventually fixes the bug.

**Comment by bdeweygit** [comment]
Fix is [here](https://github.com/bdeweygit/unity-swiftui/commit/bcb1dd12adb810e85ff24d6454e3434631058822).
